name: "Configure ssl-cert on gateway"

on:
  workflow_dispatch:
    inputs:
      kv_name:
        description: Name of the Vault
        required: true
      cert_name:
        description: Name of the Certificate
        required: true
      agw_name:
        description: Name of Application Gateway
        required: true
      agw_rg_name:
        description: Name of Application Gateway Resource Group
        required: true
      ssl_cert_name:
        description: ssl-cert Name on Application Gateway
        required: true
jobs:

  configure-ssl-cert-on-gateway:
    name: "Create ssl-cert"
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
                
    - name: Create KV Secret
      uses: azure/CLI@v1
      with:
        inlineScript: |
          KV_NAME=${{ github.event.inputs.kv_name }}
          CERT_NAME=${{ github.event.inputs.cert_name }}
          VERSIONED_SECRET_ID=$(az keyvault certificate show -n $CERT_NAME --vault-name $KV_NAME --query "sid" -o tsv)
          UNVERSIONED_SECRET_ID=$(echo $VERSIONED_SECRET_ID | cut -d'/' -f-5)
          az network application-gateway ssl-cert create -n ${{ github.event.inputs.ssl_cert_name }} --gateway-name ${{ github.event.inputs.agw_name }} --resource-group ${{ github.event.inputs.agw_rg_name }} --key-vault-secret-id $UNVERSIONED_SECRET_ID
